# i_group.py - Infrastructure management software

from typing import Dict, List, Optional, Set, Tuple
from collections import defaultdict
from common import *

class TrafficSignalController:
    """Controls traffic signals at intersections"""
    
    def __init__(self):
        self.signals: Dict[Tuple[int, int, Direction], SignalState] = {}
        self.current_green: Dict[Tuple[int, int], Direction] = {}
        # Starvation counter: tracks how many steps each direction has had
        # demand > 0 but was not granted GREEN.  Used to boost effective demand
        # and prevent perpetual priority inversion between EAST and WEST.
        self.direction_wait_steps: Dict[Tuple[int, int, Direction], int] = defaultdict(int)
        
        # Initialize signals to RED — only for valid arrival directions at each intersection
        for x in range(-1, 3):
            for y in range(3):
                if x == -1 and y != 0:
                    continue
                for direction in RoadNetwork.get_valid_arrival_directions(x, y):
                    self.signals[(x, y, direction)] = SignalState.RED
    
    def get_intersection_demand(self, vehicle_states: List[VehicleState]) -> Dict[Tuple[int, int, Direction], int]:
        """Calculate demand for each intersection arrival direction.

        Demand is generated by vehicles waiting at the last slot of a road
        segment (about to cross the upcoming intersection).  Vehicles never
        occupy intersection nodes, so there is no separate at-intersection case.
        """
        demand = defaultdict(int)

        for vs in vehicle_states:
            pos = vs.position
            if pos.slot == RoadNetwork.get_max_slots(pos.x, pos.y, pos.direction):
                intersection = pos.get_intersection()
                if pos.direction == Direction.EAST:
                    next_intersection = (intersection[0] + 1, intersection[1])
                elif pos.direction == Direction.WEST:
                    next_intersection = (intersection[0] - 1, intersection[1])
                elif pos.direction == Direction.SOUTH:
                    next_intersection = (intersection[0], intersection[1] + 1)
                else:  # NORTH
                    next_intersection = (intersection[0], intersection[1] - 1)
                demand[(next_intersection[0], next_intersection[1], pos.direction)] += 1

        return demand
    
    def detect_conflicts(self, vehicle_states: List[VehicleState]) -> Set[Tuple[int, int]]:
        """Detect intersections where multiple vehicles are waiting to cross"""
        conflicts = set()

        # Group vehicles by the intersection they are approaching (at last slot)
        intersection_vehicles = defaultdict(list)
        for vs in vehicle_states:
            pos = vs.position
            max_slots = RoadNetwork.get_max_slots(pos.x, pos.y, pos.direction)
            if pos.slot == max_slots:
                if pos.direction == Direction.EAST:
                    next_int = (pos.x + 1, pos.y)
                elif pos.direction == Direction.WEST:
                    next_int = (pos.x - 1, pos.y)
                elif pos.direction == Direction.SOUTH:
                    next_int = (pos.x, pos.y + 1)
                else:  # NORTH
                    next_int = (pos.x, pos.y - 1)
                intersection_vehicles[next_int].append(vs)

        for intersection, vehicles in intersection_vehicles.items():
            if len(vehicles) > 1:
                conflicts.add(intersection)

        return conflicts
    
    def update_signals(self, vehicle_states: List[VehicleState], time_step: int):
        """Update traffic signals based on current vehicle positions"""

        demand = self.get_intersection_demand(vehicle_states)

        # Starvation boost: each step a direction waits with demand>0 but no
        # green, its effective demand grows.  This guarantees every active
        # direction is eventually served regardless of competing traffic volume.
        STARVATION_THRESHOLD = 2  # steps before demand starts to be boosted

        for x in range(-1, 3):
            for y in range(3):
                if x == -1 and y != 0:
                    continue

                intersection = (x, y)
                valid_arrivals = RoadNetwork.get_valid_arrival_directions(x, y)

                # Compute effective demand = base + starvation bonus
                eff: Dict[Direction, int] = {}
                for direction in valid_arrivals:
                    base = demand.get((x, y, direction), 0)
                    if base > 0:
                        wait = self.direction_wait_steps.get((x, y, direction), 0)
                        eff[direction] = base + wait // STARVATION_THRESHOLD
                    else:
                        eff[direction] = 0

                directions_demand = sorted(eff.items(), key=lambda kv: kv[1], reverse=True)

                if directions_demand and directions_demand[0][1] > 0:
                    chosen_direction = directions_demand[0][0]

                    # Apply GREEN for chosen direction; all others RED
                    for direction in valid_arrivals:
                        self.signals[(x, y, direction)] = SignalState.RED
                    self.signals[(x, y, chosen_direction)] = SignalState.GREEN
                    self.current_green[intersection] = chosen_direction

                    # Reset starvation counter for served direction;
                    # accumulate for other active directions.
                    self.direction_wait_steps[(x, y, chosen_direction)] = 0
                    for d in valid_arrivals:
                        if d != chosen_direction and demand.get((x, y, d), 0) > 0:
                            self.direction_wait_steps[(x, y, d)] += 1
                else:
                    for direction in valid_arrivals:
                        self.signals[(x, y, direction)] = SignalState.RED
                    self.current_green.pop(intersection, None)
    
    def verify_signal_constraints(self) -> Tuple[bool, str]:
        """Verify only one green signal per intersection"""
        
        for x in range(-1, 3):
            for y in range(3):
                if x == -1 and y != 0:
                    continue

                green_count = 0
                for direction in RoadNetwork.get_valid_arrival_directions(x, y):
                    if self.signals.get((x, y, direction)) == SignalState.GREEN:
                        green_count += 1

                if green_count > 1:
                    return False, f"Multiple green signals at intersection ({x}, {y})"
        
        return True, "OK"
    
    def get_infrastructure_state(self, time_step: int) -> InfrastructureState:
        """Get current infrastructure state for v-group"""
        return InfrastructureState(
            signals=self.signals.copy(),
            time_step=time_step
        )

class InfrastructureManager:
    """Main infrastructure management system"""

    def __init__(self):
        self.signal_controller = TrafficSignalController()
        self.time_step = 0

        # Violation counters
        self.collision_count = 0
        self.red_light_count = 0
        self.uturn_count = 0
        self.wrong_lane_count = 0

        # Previous-step state for violation detection
        self._prev_positions: Dict[int, Position] = {}
        self._prev_infra_state: Optional[InfrastructureState] = None

    # ------------------------------------------------------------------
    # Violation detection (called before computing new signals)
    # ------------------------------------------------------------------

    def _detect_violations(self, vehicle_states: List[VehicleState]):
        """Compare current vehicle_states against _prev_positions to find violations.

        - Collision   : two vehicles share the same Position in the current step.
        - Red light   : vehicle moved from last slot (prev) to slot 1 (curr) and
                        the signal in _prev_infra_state for that crossing was RED.
        - U-turn      : vehicle's current direction is the opposite of its previous
                        direction.

        Vehicles that completed their tour (present in _prev_positions but absent
        from vehicle_states) are checked only for red-light violations (they must
        have crossed back to Point A on GREEN).
        """
        if not self._prev_positions:
            return  # Nothing to compare on the first step

        curr_map: Dict[int, Position] = {vs.id: vs.position for vs in vehicle_states}

        # ---- Collision ------------------------------------------------
        seen: Dict[Position, int] = {}
        for vid, pos in curr_map.items():
            if pos in seen:
                self.collision_count += 1
            else:
                seen[pos] = vid

        # ---- Red-light & U-turn --------------------------------------
        def _next_intersection(prev_pos: Position) -> Optional[Tuple[int, int]]:
            max_slots = RoadNetwork.get_max_slots(
                prev_pos.x, prev_pos.y, prev_pos.direction)
            if prev_pos.slot != max_slots:
                return None
            d = prev_pos.direction
            if d == Direction.EAST:   return (prev_pos.x + 1, prev_pos.y)
            if d == Direction.WEST:   return (prev_pos.x - 1, prev_pos.y)
            if d == Direction.SOUTH:  return (prev_pos.x, prev_pos.y + 1)
            return (prev_pos.x, prev_pos.y - 1)

        for vid, prev_pos in self._prev_positions.items():
            curr_pos = curr_map.get(vid)

            if curr_pos is not None:
                # Check U-turn (direction reversed)
                if curr_pos.direction == prev_pos.direction.opposite():
                    self.uturn_count += 1
                # Check wrong-lane (backward slot movement on same segment)
                elif (curr_pos.direction == prev_pos.direction
                      and curr_pos.x == prev_pos.x
                      and curr_pos.y == prev_pos.y
                      and curr_pos.slot < prev_pos.slot):
                    self.wrong_lane_count += 1

                # Check red-light: crossed an intersection this step?
                prev_max = RoadNetwork.get_max_slots(
                    prev_pos.x, prev_pos.y, prev_pos.direction)
                if prev_pos.slot == prev_max and curr_pos.slot == 1:
                    if self._prev_infra_state is not None:
                        intersection = _next_intersection(prev_pos)
                        if intersection is not None:
                            sig = self._prev_infra_state.signals.get(
                                (intersection[0], intersection[1], prev_pos.direction))
                            if sig == SignalState.RED:
                                self.red_light_count += 1
            else:
                # Vehicle completed its tour — check if it crossed back to A on RED
                intersection = _next_intersection(prev_pos)
                if intersection is not None and self._prev_infra_state is not None:
                    sig = self._prev_infra_state.signals.get(
                        (intersection[0], intersection[1], prev_pos.direction))
                    if sig == SignalState.RED:
                        self.red_light_count += 1

    # ------------------------------------------------------------------
    # Public violation report
    # ------------------------------------------------------------------

    def get_violation_report(self) -> Dict[str, int]:
        """Return current violation counts as a dict."""
        total = (self.collision_count + self.red_light_count
                 + self.uturn_count + self.wrong_lane_count)
        return {
            'collision':   self.collision_count,
            'red_light':   self.red_light_count,
            'uturn':       self.uturn_count,
            'wrong_lane':  self.wrong_lane_count,
            'total':       total,
        }

    def print_violation_report(self):
        """Print a formatted summary of detected violations."""
        r = self.get_violation_report()
        print("=" * 50)
        print("I-GROUP VIOLATION REPORT")
        print("=" * 50)
        print(f"  Collisions:       {r['collision']}")
        print(f"  Red-light runs:   {r['red_light']}")
        print(f"  U-turns:          {r['uturn']}")
        print(f"  Wrong lane:       {r['wrong_lane']}")
        print(f"  Total violations: {r['total']}")
        if r['total'] == 0:
            print("  ✓ No violations detected")
        else:
            print("  ✗ Violations detected")
        print("=" * 50)

    # ------------------------------------------------------------------
    # Main processing loop
    # ------------------------------------------------------------------

    def process_vehicle_states(self, vehicle_states: List[VehicleState]) -> InfrastructureState:
        """Process vehicle states and return infrastructure state."""

        # Detect violations before updating signals (uses previous infra_state)
        self._detect_violations(vehicle_states)

        # Update traffic signals
        self.signal_controller.update_signals(vehicle_states, self.time_step)

        # Verify signal invariant
        valid, message = self.signal_controller.verify_signal_constraints()
        if not valid:
            print(f"WARNING: Signal constraint violation: {message}")

        # Produce infrastructure state
        infra_state = self.signal_controller.get_infrastructure_state(self.time_step)

        # Save state for next-step violation detection
        self._prev_positions = {vs.id: vs.position for vs in vehicle_states}
        self._prev_infra_state = infra_state

        self.time_step += 1

        return infra_state
